add commit format check

diff --git a/.github/workflows/check-pr.yml b/.github/workflows/check-pr.yml
--- a/.github/workflows/check-pr.yml
+++ b/.github/workflows/check-pr.yml
@@ -48,27 +48,33 @@ jobs:
               pull_number: context.payload.number,
             });
             console.log(JSON.stringify(result));
-            return result.data[0].commit.message;
+            return result.data[0].commit.message.split("\n")[0]; // 只截取 commit message 第一行
 
-      - name: print the info of the latest commit
+
+      - name: check commit message
         run: |
           echo "The commit message:"
           echo "${{ steps.get-latest-commit.outputs.result }}"
 
-          if [ "${{ steps.get-latest-commit.outputs.result }}" == "" ];then
-            echo "list commits error"
+          if [[ ! "$str" =~ ^新增:( [^ ]+){1,}$ ]]; then
+            echo '提交信息请用 新增: 开头, 请仔细阅读第三步。'
             exit 1
           fi
 
-          if [ "${{ steps.get-latest-commit.outputs.result }}" == "undefined" ];then
-            echo "list commits error"
-            exit 1
-          fi
+          # if [ "${{ steps.get-latest-commit.outputs.result }}" == "" ];then
+          #   echo "list commits error"
+          #   exit 1
+          # fi
 
-          if [ "${{ steps.get-latest-commit.outputs.result }}" == "Update list.csv" ];then
-            echo "修改提交时的提交信息不要是默认的 Update list.csv，请仔细阅读第三步。"
-            exit 1
-          fi
+          # if [ "${{ steps.get-latest-commit.outputs.result }}" == "undefined" ];then
+          #   echo "list commits error"
+          #   exit 1
+          # fi
+
+          # if [ "${{ steps.get-latest-commit.outputs.result }}" == "Update list.csv" ];then
+          #   echo "修改提交时的提交信息不要是默认的 Update list.csv，请仔细阅读第三步。"
+          #   exit 1
+          # fi
 
       - name: Check out code into the Go module directory
         uses: actions/checkout@v2
